### PR TITLE
rg - copied files from team02

### PR DESCRIPTION
**Pull request by roberto-garcia-0**
# Overview

This PR copies team02 backend code to the team03 starter.

### CODE REVIEW

**Comment by haoyuanli2023** [comment]
Do we need to copy all 6 files from team02 or just 1 individual working on? I see you copied all 6.

**Comment by roberto-garcia-0** [comment]
> Do we need to copy all 6 files from team02 or just 1 individual working on? I see you copied all 6.

@haoyuanli2023 All 6 are going to be in the final version anyway, so it would be easier to PR all of them at once instead of one by one.

**Comment by haoyuanli2023** [comment]
Great! It looks good to me. I think it's ready to merge.

**Comment by SawyerEssabhoy** [comment]
Looks good, I'll merge it

**Pull request merged**
